# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AlterField(
            model_name='points',
            name='date_created',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AUser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='auser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
    ]
