# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170127_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='date_created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='auser',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='date_created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
