# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170127_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
