# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170130_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='auser',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='point',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
